### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by born2snipe** [DaanVanYperen/odb-dynasty#1]
I cloned your project and I am attempting to run the desktop version and I am receiving the following error: 

`Exception in thread "LWJGL Application" com.artemis.InvalidComponentException: EntitySpawner: missing public constructor
    at com.artemis.ComponentTypeFactory.createComponentType(ComponentTypeFactory.java:65)
    at com.artemis.ComponentTypeFactory.getTypeFor(ComponentTypeFactory.java:54)
    at com.artemis.ComponentTypeFactory.getIndexFor(ComponentTypeFactory.java:100)
    at com.artemis.Aspect$Builder.associate(Aspect.java:357)
    at com.artemis.Aspect$Builder.build(Aspect.java:348)
    at com.artemis.EntitySubscription.<init>(EntitySubscription.java:28)
    at com.artemis.AspectSubscriptionManager.createSubscription(AspectSubscriptionManager.java:58)
    at com.artemis.AspectSubscriptionManager.get(AspectSubscriptionManager.java:54)
    at com.artemis.BaseEntitySystem.getSubscription(BaseEntitySystem.java:51)
    at com.artemis.BaseEntitySystem.setWorld(BaseEntitySystem.java:41)
    at com.artemis.EntitySystem.setWorld(EntitySystem.java:54)
    at com.artemis.WorldConfiguration.initialize(WorldConfiguration.java:168)
    at com.artemis.World.<init>(World.java:86)
    at net.mostlyoriginal.game.screen.GameScreen.createWorld(GameScreen.java:114)
    at net.mostlyoriginal.api.screen.core.WorldScreen.show(WorldScreen.java:24)
    at com.badlogic.gdx.Game.setScreen(Game.java:61)
    at net.mostlyoriginal.game.GdxArtemisGame.restart(GdxArtemisGame.java:21)
    at net.mostlyoriginal.game.GdxArtemisGame.create(GdxArtemisGame.java:14)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.artemis.utils.reflect.ReflectionException: Constructor not found for class: net.mostlyoriginal.api.component.script.EntitySpawner
    at com.artemis.utils.reflect.ClassReflection.getConstructor(ClassReflection.java:91)
    at com.artemis.ComponentTypeFactory.createComponentType(ComponentTypeFactory.java:61)
    ... 19 more
Caused by: java.lang.NoSuchMethodException: net.mostlyoriginal.api.component.script.EntitySpawner.<init>()
    at java.lang.Class.getConstructor0(Class.java:2971)
    at java.lang.Class.getConstructor(Class.java:1812)
    at com.artemis.utils.reflect.ClassReflection.getConstructor(ClassReflection.java:87)
    ... 20 more`

Should "artemis" be able to construct a component with a non-default constructor?

**Comment by DaanVanYperen** [comment]
I fixed some issues in artemis-odb-contrib that are not published to maven repositories yet. Will have to push out a new version to get this fixed. If you know how you could install it locally for now!
https://github.com/DaanVanYperen/artemis-odb-contrib/tree/develop

**Comment by born2snipe** [comment]
Thank you, that was it!
